// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using heraguard.Infrastructure.Data;

#nullable disable

namespace heraguard.Infrastructure.Migrations
{
    [DbContext(typeof(HeraGuardDbContext))]
    [Migration("20251108040753_AddRelationship")]
    partial class AddRelationship
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("heraguard.Domain.Entities.Activity", b =>
                {
                    b.Property<Guid>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CaregiverId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ElderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<TimeSpan>("RecommendedTime")
                        .HasColumnType("interval");

                    b.HasKey("ActivityId");

                    b.HasIndex("CaregiverId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("ElderId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("heraguard.Domain.Entities.CaregiverProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Caregivers");
                });

            modelBuilder.Entity("heraguard.Domain.Entities.DoctorProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("MedicalCenter")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MedicalLicense")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("heraguard.Domain.Entities.ElderProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmergencyContact")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LinkingCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Elders");
                });

            modelBuilder.Entity("heraguard.Domain.Entities.MedicalAppointment", b =>
                {
                    b.Property<Guid>("MedicalAppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CaregiverId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ElderId")
                        .HasColumnType("uuid");

                    b.Property<string>("NameOfPatient")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time without time zone");

                    b.HasKey("MedicalAppointmentId");

                    b.HasIndex("CaregiverId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("ElderId");

                    b.ToTable("MedicalAppointments");
                });

            modelBuilder.Entity("heraguard.Domain.Entities.Medication", b =>
                {
                    b.Property<Guid>("MedicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CaregiverId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<Guid>("ElderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Frequency")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PrescriptionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MedicationId");

                    b.HasIndex("CaregiverId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("ElderId");

                    b.HasIndex("PrescriptionId");

                    b.ToTable("Medications");
                });

            modelBuilder.Entity("heraguard.Domain.Entities.Prescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ElderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("ElderId");

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("heraguard.Domain.Entities.Relationship", b =>
                {
                    b.Property<Guid>("RelationshipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ElderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RelatedUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("RelationshipTypeId")
                        .HasColumnType("integer");

                    b.HasKey("RelationshipId");

                    b.HasIndex("ElderId");

                    b.HasIndex("RelatedUserId");

                    b.ToTable("Relationships");
                });

            modelBuilder.Entity("heraguard.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("heraguard.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("heraguard.Domain.Entities.Activity", b =>
                {
                    b.HasOne("heraguard.Domain.Entities.CaregiverProfile", "CaregiverProfile")
                        .WithMany()
                        .HasForeignKey("CaregiverId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("heraguard.Domain.Entities.DoctorProfile", "DoctorProfile")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("heraguard.Domain.Entities.ElderProfile", "ElderProfile")
                        .WithMany()
                        .HasForeignKey("ElderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CaregiverProfile");

                    b.Navigation("DoctorProfile");

                    b.Navigation("ElderProfile");
                });

            modelBuilder.Entity("heraguard.Domain.Entities.CaregiverProfile", b =>
                {
                    b.HasOne("heraguard.Domain.Entities.User", "User")
                        .WithOne("FamiliarProfile")
                        .HasForeignKey("heraguard.Domain.Entities.CaregiverProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("heraguard.Domain.Entities.DoctorProfile", b =>
                {
                    b.HasOne("heraguard.Domain.Entities.User", "User")
                        .WithOne("DoctorProfile")
                        .HasForeignKey("heraguard.Domain.Entities.DoctorProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("heraguard.Domain.Entities.ElderProfile", b =>
                {
                    b.HasOne("heraguard.Domain.Entities.User", "User")
                        .WithOne("AdultoMayorProfile")
                        .HasForeignKey("heraguard.Domain.Entities.ElderProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("heraguard.Domain.Entities.MedicalAppointment", b =>
                {
                    b.HasOne("heraguard.Domain.Entities.CaregiverProfile", "CaregiverProfile")
                        .WithMany()
                        .HasForeignKey("CaregiverId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("heraguard.Domain.Entities.DoctorProfile", "DoctorProfile")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("heraguard.Domain.Entities.ElderProfile", "ElderProfile")
                        .WithMany()
                        .HasForeignKey("ElderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CaregiverProfile");

                    b.Navigation("DoctorProfile");

                    b.Navigation("ElderProfile");
                });

            modelBuilder.Entity("heraguard.Domain.Entities.Medication", b =>
                {
                    b.HasOne("heraguard.Domain.Entities.CaregiverProfile", "CaregiverProfile")
                        .WithMany()
                        .HasForeignKey("CaregiverId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("heraguard.Domain.Entities.DoctorProfile", "DoctorProfile")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("heraguard.Domain.Entities.ElderProfile", "ElderProfile")
                        .WithMany()
                        .HasForeignKey("ElderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("heraguard.Domain.Entities.Prescription", "Prescription")
                        .WithMany("Medications")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaregiverProfile");

                    b.Navigation("DoctorProfile");

                    b.Navigation("ElderProfile");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("heraguard.Domain.Entities.Prescription", b =>
                {
                    b.HasOne("heraguard.Domain.Entities.DoctorProfile", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId");

                    b.HasOne("heraguard.Domain.Entities.ElderProfile", "Elder")
                        .WithMany()
                        .HasForeignKey("ElderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Elder");
                });

            modelBuilder.Entity("heraguard.Domain.Entities.Relationship", b =>
                {
                    b.HasOne("heraguard.Domain.Entities.User", "Elder")
                        .WithMany()
                        .HasForeignKey("ElderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("heraguard.Domain.Entities.User", "RelatedUser")
                        .WithMany()
                        .HasForeignKey("RelatedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Elder");

                    b.Navigation("RelatedUser");
                });

            modelBuilder.Entity("heraguard.Domain.Entities.User", b =>
                {
                    b.HasOne("heraguard.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("heraguard.Domain.Entities.Prescription", b =>
                {
                    b.Navigation("Medications");
                });

            modelBuilder.Entity("heraguard.Domain.Entities.User", b =>
                {
                    b.Navigation("AdultoMayorProfile");

                    b.Navigation("DoctorProfile");

                    b.Navigation("FamiliarProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
